### ISSUE TITLE
Create a folder for every site/project

### ISSUE THREAD

**Issue by rodrigograca31** [kost/dvcs-ripper#11]
It should create a new folder with the website name everytime that it's executed....

Otherwise I can't get more than 1 site.... Both create the .git folder....

The `sqlmap` project does this... it has a folder called `output` where it creates folders like `"example.com", "google.com"*, ....`

Thanks!

**Comment by rodrigograca31** [comment]
I'm trying to implent this.... But it's my first time writing code in Perl....

So far, I've added
```perl
use URI ();
```
and then:
```perl
my $url = URI->new( $config{'url'} );
mkdir $url->host;
```
before: 
```perl
my $gd=$config{'gitdir'}."/";
```
which I was trying to modify to something like this:
```perl
my $gd=$url->host."/".$config{'gitdir'}."/";
```
But then it stops working.... (It doesn't download the repo).... 

Help? :)

**Comment by kost** [comment]
Your request is implemented as part of BHEU2015 release:
https://www.blackhat.com/eu-15/arsenal.html#dvcs-ripper

Just use -m -o /dir/where/you/want/to/store - Here's examples:

Download git tree to specific output dir:

`rip-git.pl -o /my/previously/made/dir -v -u http://www.example.com/.git/`

Download git tree to specific output dir (creating dir http__www.example.com_.git_ for url):

`rip-git.pl -m -o /dir -v -u http://www.example.com/.git/`

**Comment by rodrigograca31** [comment]
@kost Nicely done!

I would prefer if this was automatic (no flags needed) but it's ok like this....

I will test it later :)
