### ISSUE TITLE
todo: Support for brute forcing pack names

### ISSUE THREAD

**Issue by trin4ik** [kost/dvcs-ripper#12]
ORLY? This is possible for git?

**Comment by kost** [comment]
Hello!

Yes, it is possible. But it would be slow to guess it by just brute force.

Actually there are two ways:
1) Guess the name intelligently: git pack name is a hash of the sorted object names to make the resulting filename based on the pack content. That means that if there's not too much objects, we can try combination of each objects (sorted) and guess the name of the packed content. This method will not work if there's too much dependencies between objects.

2)Really brute force all combinations. This will take longer, but success rate would be 100%.

Take a look at this issue for longer explanation:
https://github.com/kost/dvcs-ripper/issues/6

I was working on this and have something on my local machine, but did not push it to the repo yet.

**Comment by trin4ik** [comment]
We can get a list of all objects + to understand what we are lacking. The only problem is that we do not know how often the collected packs. Faced with this problem, the solution is not found, brute did not help me. Perhaps you will, report)

**Comment by kost** [comment]
Hello! You can take a look at two new methods:
- Inteligent guessing of packed refs (does not work always, depends on missing refs!)
- pure brute forcing of packed refs (works, but slow!)
