### ISSUE TITLE
Ignore SSL warnings

### ISSUE THREAD

**Issue by gsingh93** [kost/dvcs-ripper#14]
I tried using this on a site with a broken HTTPS cert, and it was throwing errors. You should probably ignore these errors instead.

**Comment by kost** [comment]
Could you please copy/paste errors you're getting? Thanks in advance!

**Comment by gsingh93** [comment]
Each request fails with a message like this:

```
[!] Not found for COMMIT_EDITMSG: 500 Can't connect to site.com:443 (certificate verify failed)
```

I don't want to share the site name, but the issue with the cert is that doesn't match the site name. In any case, all SSL errors should be ignored (i.e. self signed certs, invalid certs, etc.).

**Comment by kost** [comment]
No need for site name.

Just sanity check. Have you used "-s" switch to turn off SSL verification?
Could you provide your full command line (obviously without offeninding
URL)?

Thanks in advance,

On Fri, Nov 20, 2015 at 9:10 PM, Gulshan Singh <notifications@github.com>
wrote:

> Each request fails with a message like this:
>
> [!] Not found for COMMIT_EDITMSG: 500 Can't connect to site.com:443 (certificate verify failed)
>
> I don't want to share the site name, but the issue with the cert is that
> doesn't match the site name. In any case, all SSL errors should be ignored
> (i.e. self signed certs, invalid certs, etc.).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kost/dvcs-ripper/issues/14#issuecomment-158512068>.
>



-- 
Vlatko Kosturjak, Kost

**Comment by gsingh93** [comment]
Using the `-s` flag worked. Thanks for the help!
