### ISSUE TITLE
Turn off SSL verification

### ISSUE THREAD

**Issue by SergeC** [kost/dvcs-ripper#4]
Hi. Can you please turn off SSL verification? Or how can I use this tool over https?
Directory index is enabled and requested files 100% exists.
Here is my log:
➜  ../rip-git.pl -v -u https://qwe.to/.git/
[i] Downloading git files from https://qwe.to/.git/
[!] Not found for COMMIT_EDITMSG: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
[!] Not found for config: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
[!] Not found for description: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
[!] Not found for HEAD: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
[!] Not found for index: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
[!] Not found for packed-refs: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
[!] Not found for objects/info/alternates: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
[!] Not found for info/grafts: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
[!] Not found for logs/HEAD: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
[!] Not found for objects/ve/rify: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
[!] Not found for objects//: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
[!] Not found for objects/pr/oblem: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
[!] Not found for objects/va/riable: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
[!] Not found for objects//: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
[!] Not found for objects/di/sable: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
[!] Not found for objects/va/riable: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
[!] Not found for objects/wi/th: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
[!] Not found for refs/heads/master: 500 Can't verify SSL peers without knowing which Certificate Authorities to trust
[i] Running git fsck to check for missing items
Checking object directories: 100% (256/256), done.
[i] Got items with git fsck: 0
[i] Items fetched: 0
Your branch is up-to-date with 'origin/master'.

**Comment by kost** [comment]
Thanks on reporting. If you have IO::Socket::SSL earlier than 1.79 you can
do something like:

PERL_LWP_SSL_VERIFY_HOSTNAME=0 ../rip-git.pl -v -u https://qwe.to/.git/

On Thu, Jun 18, 2015 at 12:23 PM, SergeC <notifications@github.com> wrote:

> Hi. Can you please turn off SSL verification? Or how can I use this tool
> over https?
> Directory index is enabled and requested files 100% exists.
> Here is my log:
> ➜ ../rip-git.pl -v -u https://qwe.to/.git/
> [i] Downloading git files from http://qwe.to/.git/
> [!] Not found for COMMIT_EDITMSG: 500 Can't verify SSL peers without
> knowing which Certificate Authorities to trust
> [!] Not found for config: 500 Can't verify SSL peers without knowing which
> Certificate Authorities to trust
> [!] Not found for description: 500 Can't verify SSL peers without knowing
> which Certificate Authorities to trust
> [!] Not found for HEAD: 500 Can't verify SSL peers without knowing which
> Certificate Authorities to trust
> [!] Not found for index: 500 Can't verify SSL peers without knowing which
> Certificate Authorities to trust
> [!] Not found for packed-refs: 500 Can't verify SSL peers without knowing
> which Certificate Authorities to trust
> [!] Not found for objects/info/alternates: 500 Can't verify SSL peers
> without knowing which Certificate Authorities to trust
> [!] Not found for info/grafts: 500 Can't verify SSL peers without knowing
> which Certificate Authorities to trust
> [!] Not found for logs/HEAD: 500 Can't verify SSL peers without knowing
> which Certificate Authorities to trust
> [!] Not found for objects/ve/rify: 500 Can't verify SSL peers without
> knowing which Certificate Authorities to trust
> [!] Not found for objects//: 500 Can't verify SSL peers without knowing
> which Certificate Authorities to trust
> [!] Not found for objects/pr/oblem: 500 Can't verify SSL peers without
> knowing which Certificate Authorities to trust
> [!] Not found for objects/va/riable: 500 Can't verify SSL peers without
> knowing which Certificate Authorities to trust
> [!] Not found for objects//: 500 Can't verify SSL peers without knowing
> which Certificate Authorities to trust
> [!] Not found for objects/di/sable: 500 Can't verify SSL peers without
> knowing which Certificate Authorities to trust
> [!] Not found for objects/va/riable: 500 Can't verify SSL peers without
> knowing which Certificate Authorities to trust
> [!] Not found for objects/wi/th: 500 Can't verify SSL peers without
> knowing which Certificate Authorities to trust
> [!] Not found for refs/heads/master: 500 Can't verify SSL peers without
> knowing which Certificate Authorities to trust
> [i] Running git fsck to check for missing items
> Checking object directories: 100% (256/256), done.
> [i] Got items with git fsck: 0
> [i] Items fetched: 0
> Your branch is up-to-date with 'origin/master'.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kost/dvcs-ripper/issues/4>.
>



-- 
Vlatko Kosturjak, Kost

**Comment by kost** [comment]
BTW I hope you have authorization to get that git source :-D

On Thu, Jun 18, 2015 at 1:03 PM, Vlatko Kosturjak <
vlatko.kosturjak@gmail.com> wrote:

> Thanks on reporting. If you have IO::Socket::SSL earlier than 1.79 you can
> do something like:
>
> PERL_LWP_SSL_VERIFY_HOSTNAME=0 ../rip-git.pl -v -u https://qwe.to/.git/
>
> On Thu, Jun 18, 2015 at 12:23 PM, SergeC <notifications@github.com> wrote:
>
>> Hi. Can you please turn off SSL verification? Or how can I use this tool
>> over https?
>> Directory index is enabled and requested files 100% exists.
>> Here is my log:
>> ➜ ../rip-git.pl -v -u https://qwe.to/.git/
>> [i] Downloading git files from http://qwe.to/.git/
>> [!] Not found for COMMIT_EDITMSG: 500 Can't verify SSL peers without
>> knowing which Certificate Authorities to trust
>> [!] Not found for config: 500 Can't verify SSL peers without knowing
>> which Certificate Authorities to trust
>> [!] Not found for description: 500 Can't verify SSL peers without knowing
>> which Certificate Authorities to trust
>> [!] Not found for HEAD: 500 Can't verify SSL peers without knowing which
>> Certificate Authorities to trust
>> [!] Not found for index: 500 Can't verify SSL peers without knowing which
>> Certificate Authorities to trust
>> [!] Not found for packed-refs: 500 Can't verify SSL peers without knowing
>> which Certificate Authorities to trust
>> [!] Not found for objects/info/alternates: 500 Can't verify SSL peers
>> without knowing which Certificate Authorities to trust
>> [!] Not found for info/grafts: 500 Can't verify SSL peers without knowing
>> which Certificate Authorities to trust
>> [!] Not found for logs/HEAD: 500 Can't verify SSL peers without knowing
>> which Certificate Authorities to trust
>> [!] Not found for objects/ve/rify: 500 Can't verify SSL peers without
>> knowing which Certificate Authorities to trust
>> [!] Not found for objects//: 500 Can't verify SSL peers without knowing
>> which Certificate Authorities to trust
>> [!] Not found for objects/pr/oblem: 500 Can't verify SSL peers without
>> knowing which Certificate Authorities to trust
>> [!] Not found for objects/va/riable: 500 Can't verify SSL peers without
>> knowing which Certificate Authorities to trust
>> [!] Not found for objects//: 500 Can't verify SSL peers without knowing
>> which Certificate Authorities to trust
>> [!] Not found for objects/di/sable: 500 Can't verify SSL peers without
>> knowing which Certificate Authorities to trust
>> [!] Not found for objects/va/riable: 500 Can't verify SSL peers without
>> knowing which Certificate Authorities to trust
>> [!] Not found for objects/wi/th: 500 Can't verify SSL peers without
>> knowing which Certificate Authorities to trust
>> [!] Not found for refs/heads/master: 500 Can't verify SSL peers without
>> knowing which Certificate Authorities to trust
>> [i] Running git fsck to check for missing items
>> Checking object directories: 100% (256/256), done.
>> [i] Got items with git fsck: 0
>> [i] Items fetched: 0
>> Your branch is up-to-date with 'origin/master'.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/kost/dvcs-ripper/issues/4>.
>>
>
>
>
> --
> Vlatko Kosturjak, Kost
>



-- 
Vlatko Kosturjak, Kost

**Comment by kost** [comment]
Added new options, so you can do something like:
../dvcs-ripper/rip-git.pl -s -v -u https://qwe.to/.git/

Let me know if it works for you!

BTW I don't recommend running rip-git.pl inside dvcs-ripper git tree. Make dir outside of any git tree and run rip-git.pl ...

**Comment by SergeC** [comment]
SSL connection works. Can you please update readme with new option?
I got a bunch of other errors:

error: bad graft data: </html>
error: Could not read 324324erewrewr
error: inflate: data stream error (incorrect header check)
error: unable to unpack 3432432efrdsfsdf header
error: inflate: data stream error (incorrect header check)
fatal: loose object 343243erewrew (stored in .git/objects/01/wr324324sdf) is corrupt

**Comment by kost** [comment]
Great. Glad it works. README updated.

Could you please open another issue as this is different issue than this
one? It would also help to include .git/objects/01/wr324324sdf file.

On Thu, Jun 18, 2015 at 1:38 PM, SergeC <notifications@github.com> wrote:

> SSL connection works. Can you please update readme with new option?
> I got a bunch of other errors:
>
> error: bad graft data:
> error: Could not read 324324erewrewr
> error: inflate: data stream error (incorrect header check)
> error: unable to unpack 3432432efrdsfsdf header
> error: inflate: data stream error (incorrect header check)
> fatal: loose object 343243erewrew (stored in .git/objects/01/wr324324sdf)
> is corrupt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kost/dvcs-ripper/issues/4#issuecomment-113123617>.
>



-- 
Vlatko Kosturjak, Kost
