### ISSUE TITLE
Don't follow a 301...

### ISSUE THREAD

**Issue by anonymousforker** [kost/dvcs-ripper#7]
You can likely speed this up by checking HTTP response code for 301/302 redirects and immediately skipping over instead of following them to a 404.

I adjusted the original DVCS-Pillage wget to include *--max-redirects 0* and it's much faster than dvcs-ripper.

**Comment by kost** [comment]
Hello and thanks for reporting the issue! 

Your idea is implemented in following commit https://github.com/kost/dvcs-ripper/commit/f6349602ef9b30487c4b6f5fce942347d811f539 
and it does not follow redirects by default any more. You can change that behaviour with -r 5 (where 5 is maximum number of redirects). 

As I see lot of people having problem with speed of the tool, I have implemented few more optimizations:
- parallel requests (https://github.com/kost/dvcs-ripper/issues/8)
- check if file exists already (https://github.com/kost/dvcs-ripper/issues/9)
- cache responses (200 and 404) using redis (https://github.com/kost/dvcs-ripper/commit/e1310105d2fc79eb8769e5016536e02ddf390501)

So, you can say something like this (with 10 threads as example and redis server at 127.0.0.1:6379):
```rip-git.pl -n -t 10 -e 127.0.0.1:6379 -v -u http://127.0.0.1/testgit/.git/```

If you have any other idea to speed things up - do let me know!

Thanks again!
